# ==============================================================
# = Library Web Service -
# ==============================================================

#server:
#  port: 5051

spring:
  application:
    name: LibraryWebService
  profiles:
    active: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# ==============================================================
# = Library Logging -
# ==============================================================
logging:
  file.name: logs/app-library.log
  pattern:
    console: "%d [%t] %-5level %logger{36} - %msg%n"
    file: "%d [%t] %-5level %logger{36} - %msg%n"

