# ==============================================================
# = DBMS H2 Parameters
# ==============================================================
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:librarydevdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver

server:
  port: 8081

# ==============================================================
# = Parametri Sicurezza JWT
# ==============================================================
jwt:
  secret: 123Stella

# ==============================================================
# = Parametri Logging -
# ==============================================================
logging:
  level:
    org.springframework.web: ERROR
    ch.fincons.library.repository: DEBUG
    org.springframework.security: DEBUG
