# ==============================================================
# = DBMS MYSQL Parameters
# ==============================================================
spring:
  datasource:
    initialization-mode: always
    platform: mysql
    url: jdbc:mysql://localhost:3306/libreria
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    
server:
  port: 8082

# ==============================================================
# = Parametri Logging -
# ==============================================================
logging:
  level:
    org.springframework.web: ERROR
    ch.fincons.library.repository: ERROR
    org.springframework.security: ERROR

