# ==============================================================
# = DBMS MYSQL Parameters
# ==============================================================
spring:
  h2:
    console:
      enabled: false
      path: /h2-console
  datasource:
    initialization-mode: always
    platform: mysql
    url: jdbc:mysql://localhost:3306/libreria
    username: root
    password: Admin.01
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    
server:
  port: 8083

# ==============================================================
# = Parametri Sicurezza JWT
# ==============================================================
jwt:
  secret: 123Stella
  
# ==============================================================
# = Parametri Logging -
# ==============================================================
logging:
  level:
    org.springframework.web: ERROR
    ch.fincons.library.repository: ERROR
    org.springframework.security: ERROR
