# ==============================================================
# = DBMS H2 Parameters
# ==============================================================
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:librarydevdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver

server:
  port: 8081

# ==============================================================
# = Parametri Sicurezza JWT
# ==============================================================
jwt:
  secret: 123Stella

logging:
  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    ch.fincons.library.repository: DEBUG
    org.springframework.security: DEBUG
