# ==============================================================
# = Library Web Service -
# ==============================================================

#server:
#  port: 5051

spring:
  application:
    name: LibraryWebService
  profiles:
    active: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

